In [48]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

import numpy as np
import pandas as pd

header = ['user_id', 'item_id', 'rating', 'timestamp']
drivePrefix = '/content/gdrive/My Drive/1301174046_MF_MovieLens/'
driveSuffix = 'ml-latest-small/ratings.csv'
df = pd.read_csv(drivePrefix + driveSuffix, sep=',', names =header, skiprows=1)

n_users = df.user_id.unique().shape[0]
n_items = df.item_id.unique().shape[0]
print('Number of users = ' + str(n_users) + ' | number of movies = ' + str(n_items))
print(df)

Mounted at /content/gdrive
Number of users = 610 | number of movies = 9724
        user_id  item_id  rating   timestamp
0             1        1     4.0   964982703
1             1        3     4.0   964981247
2             1        6     4.0   964982224
3             1       47     5.0   964983815
4             1       50     5.0   964982931
...         ...      ...     ...         ...
100831      610   166534     4.0  1493848402
100832      610   168248     5.0  1493850091
100833      610   168250     5.0  1494273047
100834      610   168252     5.0  1493846352
100835      610   170875     3.0  1493846415

[100836 rows x 4 columns]


In [49]:
df = df.pivot(index='user_id', columns='item_id', values='rating')
df

item_id  1       2       3       4       ...  193583  193585  193587  193609
user_id                                  ...                                
1           4.0     NaN     4.0     NaN  ...     NaN     NaN     NaN     NaN
2           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4           NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
5           4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
...         ...     ...     ...     ...  ...     ...     ...     ...     ...
606         2.5     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
607         4.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
608         2.5     2.0     2.0     NaN  ...     NaN     NaN     NaN     NaN
609         3.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
610         5.0     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

[610 rows x 9724 columns]

In [50]:
df = df.fillna(0)
df

item_id  1       2       3       4       ...  193583  193585  193587  193609
user_id                                  ...                                
1           4.0     0.0     4.0     0.0  ...     0.0     0.0     0.0     0.0
2           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
3           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
4           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
5           4.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
...         ...     ...     ...     ...  ...     ...     ...     ...     ...
606         2.5     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
607         4.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
608         2.5     2.0     2.0     0.0  ...     0.0     0.0     0.0     0.0
609         3.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0
610         5.0     0.0     0.0     0.0  ...     0.0     0.0     0.0     0.0

[610 rows x 9724 columns]

In [52]:
MF = df.to_numpy()
MF

array([[4. , 0. , 4. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [2.5, 2. , 2. , ..., 0. , 0. , 0. ],
       [3. , 0. , 0. , ..., 0. , 0. , 0. ],
       [5. , 0. , 0. , ..., 0. , 0. , 0. ]])

In [0]:
def matrix_factorization(R, P, Q, K, steps=8, alpha=0.02, beta=0.2):
    Q = Q.T
    print(Q)
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2))

        if e < 0.001:
            break

    return P, Q.T    

In [109]:
R = MF

N = len(R)
M = len(R[0])

K = 2

P = np.random.rand(N,K)

Q = np.random.rand(M,K)

user_latent_features_1, item_latent_features_1 = matrix_factorization(R, P, Q, K)

[[0.16079579 0.36086019 0.55962791 ... 0.48607934 0.54430244 0.83218427]
 [0.13999605 0.22448955 0.11621505 ... 0.19909738 0.95289139 0.33163819]]


In [110]:
print("The original matrix")
print(R)
print("The approximation matrix by MF")
print(np.dot(user_latent_features_1, item_latent_features_1.T))

The original matrix
[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]
The approximation matrix by MF
[[3.94781446 3.79378324 3.10451832 ... 2.77534874 2.87648647 3.73507747]
 [3.48160313 3.33447983 2.71006045 ... 2.42853986 2.55193962 3.26563179]
 [3.27100839 3.46287108 3.36049481 ... 2.83923447 1.95439997 3.89775808]
 ...
 [3.83105023 3.74260468 3.16326362 ... 2.79635585 2.7094694  3.77800108]
 [3.09190289 2.9737851  2.43765213 ... 2.17788955 2.24946437 2.9316187 ]
 [4.23199634 4.07682258 3.35253208 ... 2.99193107 3.07019651 4.02894268]]


In [111]:
R = MF

N = len(R)
M = len(R[0])

K = 5

P = np.random.rand(N,K)
Q = np.random.rand(M,K)

user_latent_features_2, item_latent_features_2  = matrix_factorization(R, P, Q, K)

[[0.74152924 0.0806307  0.2414744  ... 0.77390887 0.2745295  0.93753476]
 [0.75380319 0.26094357 0.07488625 ... 0.24445959 0.19623729 0.13013701]
 [0.29670979 0.26662412 0.48083378 ... 0.04924758 0.40212369 0.55846063]
 [0.27152949 0.05624037 0.51882237 ... 0.45050318 0.11213678 0.45544009]
 [0.53236215 0.54543807 0.33931099 ... 0.56064607 0.76129253 0.7896166 ]]


In [112]:
print("The original matrix")
print(R)
print("The approximation matrix by MF")
print(np.dot(user_latent_features_2, item_latent_features_2 .T))

The original matrix
[[4.  0.  4.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 [0.  0.  0.  ... 0.  0.  0. ]
 ...
 [2.5 2.  2.  ... 0.  0.  0. ]
 [3.  0.  0.  ... 0.  0.  0. ]
 [5.  0.  0.  ... 0.  0.  0. ]]
The approximation matrix by MF
[[3.97980854 3.74886531 3.41945787 ... 2.91157593 2.95846085 4.05070128]
 [3.37261065 3.26286761 3.15960132 ... 2.53128125 2.45442003 3.64432587]
 [3.37025721 3.46985025 2.02159183 ... 3.32431607 2.12372605 4.00733175]
 ...
 [3.99867565 3.88038075 3.1850475  ... 3.11389891 2.97209632 4.15747039]
 [3.06143004 2.90222909 2.61053465 ... 2.29258082 2.26434085 3.22450899]
 [4.18364897 3.96188335 3.5231952  ... 3.13467094 3.07879651 4.3314504 ]]


In [0]:
driveSuffix = 'ml-latest-small/'

np.savetxt(drivePrefix+driveSuffix+'k2_user.csv', user_latent_features_1, delimiter=",")
np.savetxt(drivePrefix+driveSuffix+'k2_item.csv', item_latent_features_1, delimiter=",")
np.savetxt(drivePrefix+driveSuffix+'k5_user.csv', user_latent_features_2, delimiter=",")
np.savetxt(drivePrefix+driveSuffix+'k5_item.csv', item_latent_features_2, delimiter=",")